### ISSUE TITLE
EXCEPTION: Type 'LinkedMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by chalin** [adaojunior/jsonp#4]
Hey Adão, I don't know if you'd be willing to update this package to be Dart 2 compliant? I'm currently getting the error mentioned below (this is from https://github.com/dart-lang/site-webdev/issues/1575):

> Runtime error when the [server-communication app](https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/server-communication) is executed:

```nocode
dart_sdk.js:100502 EXCEPTION: Type 'LinkedMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in strong mode
STACKTRACE: 
packages/$sdk/dev_compiler/amd/dart_sdk.js 4803:29                           throw
packages/$sdk/dev_compiler/amd/dart_sdk.js 4731:17                           castError
packages/$sdk/dev_compiler/amd/dart_sdk.js 4702:17                           as
packages/$sdk/dev_compiler/amd/dart_sdk.js 3961:19                           check_C
packages/$sdk/dev_compiler/amd/dart_sdk.js 4530:21                           _checkApply
packages/$sdk/dev_compiler/amd/dart_sdk.js 4604:14                           _checkAndCall
packages/$sdk/dev_compiler/amd/dart_sdk.js 4653:17                           callMethod
packages/$sdk/dev_compiler/amd/dart_sdk.js 4656:17                           dsend
packages/jsonpadding/jsonpadding.ddc.js 94:35                                [_createUri]
packages/jsonpadding/jsonpadding.ddc.js 101:32                               new
packages/jsonpadding/jsonpadding.ddc.js 18:12                                jsonp
packages/server_communication/src/wiki/wikipedia_service.ddc.js 19:58        search
...
```

cc @kwalrath

**Comment by adaojunior** [comment]
Hi @chalin, sure, I'll be updating this soon.

**Comment by adaojunior** [comment]
@chalin I fixed the issue you described above on `jsonpadding: ^1.0.1`. I tested with [angular-examples/server-communication](https://github.com/angular-examples/server-communication) but it is now getting the following error on [wikipedia_service.dart](https://github.com/angular-examples/server-communication/blob/master/lib/src/wiki/wikipedia_service.dart#L8)

> EXCEPTION: Type 'JsArray<dynamic>' is not a subtype of type 'FutureOr<List<String>>' in strong mode

I'm not very familiar with the changes on dart 2 so I'll take some time to get familiar with it and improve this package using the best of dart 2.

**Comment by bcko** [comment]
@chalin @adaojunior 
I just ran [server-communication](https://github.com/angular-examples/server-communication) with `jsonpadding: ^1.0.1` on my laptop. (Dart VM version: 2.0.0-dev.55.0 (Unknown timestamp) on "linux_x64").

server-communication ran successfully without the EXCEPTION error that @adaojunior got.

**Comment by bcko** [comment]
@adaojunior @chalin 
I was able to reproduce the runtime exception from my machine. I think it is giving that runtime error because of jsonp returning `Future<dynamic>`. In server-communication, jsonp is called inside `Future<List<String>> search` in wikipedia_service.dart. 

I am guessing the code is throwing a runtime exception because Dart 2 doesn't like using `dynamic` and typed stuffs together? (https://www.dartlang.org/guides/language/sound-dart#dont-use-a-dynamic-list-as-a-typed-list)

**Comment by adaojunior** [comment]
Seems like switching `Future<List<String>> search` to `Future<List> search` solves the problem on server-communication . I'm not quite sure what I can do to fix this issue on the package level.

**Comment by chalin** [comment]
Thank you both, that fixed it.
